<?php
/**
 * CustomerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * easybill REST API
 *
 * The first version of the easybill REST API. [CHANGELOG](https://api.easybill.de/rest/v1/CHANGELOG.md)  ## Authentication  You can choose between two available methods: `Basic Auth` or `Bearer Token`.  In each HTTP request, one of the following HTTP headers is required:  ``` # Basic Auth Authorization: Basic base64_encode('<email>:<api_key>') # Bearer Token Authorization: Bearer <api_key> ```  ## Limitations  ### Request Limit  * PLUS: 10 requests per minute * BUSINESS: 60 requests per minute  If the limit is exceeded, you will receive the HTTP error: `429 Too Many Requests`  ### Result Limit  All result lists are limited to 100 by default. This limit can be increased by the query parameter `limit` to a maximum of 1000.  ## Query filter  Many list resources can be filtered. In `/documents` you can filter e.g. by number with `/documents?number=111028654`. If you want to filter multiple numbers, you can either enter them separated by commas `/documents?number=111028654,222006895` or as an array  `/documents?number[]=111028654&number[]=222006895`.  **Warning**: The maximum size of an HTTP request line in bytes is 4094. If this limit is exceeded, you will receive the HTTP error: `414 Request-URI Too Large`  ### Escape commas in query  You can escape commans in query `name=Patrick\\, Peter` if you submit the header `X-Easybill-Escape: true` in your request.  ## Property login_id  This is the login of your admin or employee account.  ## Date and Date-Time format  Please use the timezone `Europe/Berlin`.  * **date** = *Y-m-d* = `2016-12-31` * **date-time** = *Y-m-d H:i:s* = `2016-12-31 03:13:37`  Date or datetime can be `null` because the attributes have been added later and the entry is older.
 *
 * OpenAPI spec version: 1.19.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CustomerTest Class Doc Comment
 *
 * @category    Class */
// * @description Customer
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Customer"
     */
    public function testCustomer()
    {
    }

    /**
     * Test attribute "acquire_options"
     */
    public function testPropertyAcquireOptions()
    {
    }

    /**
     * Test attribute "bank_account"
     */
    public function testPropertyBankAccount()
    {
    }

    /**
     * Test attribute "bank_account_owner"
     */
    public function testPropertyBankAccountOwner()
    {
    }

    /**
     * Test attribute "bank_bic"
     */
    public function testPropertyBankBic()
    {
    }

    /**
     * Test attribute "bank_code"
     */
    public function testPropertyBankCode()
    {
    }

    /**
     * Test attribute "bank_iban"
     */
    public function testPropertyBankIban()
    {
    }

    /**
     * Test attribute "bank_name"
     */
    public function testPropertyBankName()
    {
    }

    /**
     * Test attribute "birth_date"
     */
    public function testPropertyBirthDate()
    {
    }

    /**
     * Test attribute "cash_allowance"
     */
    public function testPropertyCashAllowance()
    {
    }

    /**
     * Test attribute "cash_allowance_days"
     */
    public function testPropertyCashAllowanceDays()
    {
    }

    /**
     * Test attribute "cash_discount"
     */
    public function testPropertyCashDiscount()
    {
    }

    /**
     * Test attribute "cash_discount_type"
     */
    public function testPropertyCashDiscountType()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "delivery_city"
     */
    public function testPropertyDeliveryCity()
    {
    }

    /**
     * Test attribute "delivery_company_name"
     */
    public function testPropertyDeliveryCompanyName()
    {
    }

    /**
     * Test attribute "delivery_country"
     */
    public function testPropertyDeliveryCountry()
    {
    }

    /**
     * Test attribute "delivery_first_name"
     */
    public function testPropertyDeliveryFirstName()
    {
    }

    /**
     * Test attribute "delivery_last_name"
     */
    public function testPropertyDeliveryLastName()
    {
    }

    /**
     * Test attribute "delivery_personal"
     */
    public function testPropertyDeliveryPersonal()
    {
    }

    /**
     * Test attribute "delivery_salutation"
     */
    public function testPropertyDeliverySalutation()
    {
    }

    /**
     * Test attribute "delivery_street"
     */
    public function testPropertyDeliveryStreet()
    {
    }

    /**
     * Test attribute "delivery_suffix_1"
     */
    public function testPropertyDeliverySuffix1()
    {
    }

    /**
     * Test attribute "delivery_suffix_2"
     */
    public function testPropertyDeliverySuffix2()
    {
    }

    /**
     * Test attribute "delivery_zip_code"
     */
    public function testPropertyDeliveryZipCode()
    {
    }

    /**
     * Test attribute "emails"
     */
    public function testPropertyEmails()
    {
    }

    /**
     * Test attribute "fax"
     */
    public function testPropertyFax()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "grace_period"
     */
    public function testPropertyGracePeriod()
    {
    }

    /**
     * Test attribute "group_id"
     */
    public function testPropertyGroupId()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "info_1"
     */
    public function testPropertyInfo1()
    {
    }

    /**
     * Test attribute "info_2"
     */
    public function testPropertyInfo2()
    {
    }

    /**
     * Test attribute "internet"
     */
    public function testPropertyInternet()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "login_id"
     */
    public function testPropertyLoginId()
    {
    }

    /**
     * Test attribute "mobile"
     */
    public function testPropertyMobile()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "payment_options"
     */
    public function testPropertyPaymentOptions()
    {
    }

    /**
     * Test attribute "personal"
     */
    public function testPropertyPersonal()
    {
    }

    /**
     * Test attribute "phone_1"
     */
    public function testPropertyPhone1()
    {
    }

    /**
     * Test attribute "phone_2"
     */
    public function testPropertyPhone2()
    {
    }

    /**
     * Test attribute "postbox"
     */
    public function testPropertyPostbox()
    {
    }

    /**
     * Test attribute "postbox_city"
     */
    public function testPropertyPostboxCity()
    {
    }

    /**
     * Test attribute "postbox_country"
     */
    public function testPropertyPostboxCountry()
    {
    }

    /**
     * Test attribute "postbox_zip_code"
     */
    public function testPropertyPostboxZipCode()
    {
    }

    /**
     * Test attribute "sale_price_level"
     */
    public function testPropertySalePriceLevel()
    {
    }

    /**
     * Test attribute "salutation"
     */
    public function testPropertySalutation()
    {
    }

    /**
     * Test attribute "sepa_agreement"
     */
    public function testPropertySepaAgreement()
    {
    }

    /**
     * Test attribute "sepa_agreement_date"
     */
    public function testPropertySepaAgreementDate()
    {
    }

    /**
     * Test attribute "sepa_mandate_reference"
     */
    public function testPropertySepaMandateReference()
    {
    }

    /**
     * Test attribute "since_date"
     */
    public function testPropertySinceDate()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "suffix_1"
     */
    public function testPropertySuffix1()
    {
    }

    /**
     * Test attribute "suffix_2"
     */
    public function testPropertySuffix2()
    {
    }

    /**
     * Test attribute "tax_number"
     */
    public function testPropertyTaxNumber()
    {
    }

    /**
     * Test attribute "tax_options"
     */
    public function testPropertyTaxOptions()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "vat_identifier"
     */
    public function testPropertyVatIdentifier()
    {
    }

    /**
     * Test attribute "zip_code"
     */
    public function testPropertyZipCode()
    {
    }
}
